[project]
name = "final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scipy>=1.16.1",
]

[tool.ruff]
select = []

[dependency-groups]
dev = [
    "scipy-stubs>=1.16.1.1",
]
